FROM node:latest

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

ARG NEXT_PUBLIC_WEBSOCKET_URL
ARG NEXT_PUBLIC_API_HOST

ENV NEXT_PUBLIC_WEBSOCKET_URL=${NEXT_PUBLIC_WEBSOCKET_URL}
ENV NEXT_PUBLIC_API_HOST=${NEXT_PUBLIC_API_HOST}

CMD ["npm", "dev"]
